/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 humano.gltf
Author: Diego Luján García (https://sketchfab.com/diegoluga)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-full-body-ecorche-ab11ebff89224f03bd75efede1164cf6
Title: Male Full Body Ecorche
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

export function Model(props) {
  const { nodes, materials } = useGLTF('/humano.gltf')
  const bicepsRef = useRef();
  

  function handleBicepsClick() {
    window.location = 'https://youtube.com';
  }
  function handleHover() {
    bicepsRef.current.material.color.set("red");
  }

  function handleHoverEnd() {
    bicepsRef.current.material.color.set('white');
  }


  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* GLUTEOS */}
        <mesh 
          geometry={nodes.Object_3.geometry}
          material={materials.defaultMat_12} >
            <meshStandardMaterial />
        </mesh>
        {/* HOMBROS */}
        <mesh 
          geometry={nodes.Object_5.geometry} 
          material={materials.defaultMat_11}>

        </mesh>

        {/* GEMELOS */}
        <mesh 
          geometry={nodes.Object_7.geometry} 
          material={materials.defaultMat_10}>

        </mesh>
        
        {/* FEMORAL */}
        <mesh 
          geometry={nodes.Object_9.geometry} 
          material={materials.defaultMat_9}>

        </mesh>

        {/* NARIZ OJOS COLUMNA */}
        <mesh 
          geometry={nodes.Object_11.geometry} 
          material={materials.material_1}>

        </mesh>

        {/* ESPALDA */}
        <mesh 
        geometry={nodes.Object_13.geometry} 
        material={materials.defaultMat_8}>

        </mesh>

        {/* CARA MUSCULOS */}
        <mesh 
        geometry={nodes.Object_15.geometry} 
        material={materials.defaultMat_7}>

        </mesh>

        {/* CUADRICEPS */}
        <mesh 
        geometry={nodes.Object_17.geometry} 
        material={materials.defaultMat_6}>

        </mesh>

        {/* CUELLO */}
        <mesh 
        geometry={nodes.Object_19.geometry} 
        material={materials.defaultMat_5}>

        </mesh>

        {/* MANOS */}
        <mesh 
        geometry={nodes.Object_21.geometry} 
        material={materials.defaultMat_4}>

        </mesh>

        {/* PECHO Y ABDOMINAL */}
        <mesh 
        geometry={nodes.Object_23.geometry} 
        material={materials.defaultMat_3}>

        </mesh>

        {/* TIBIALIS (PARTE FRONTAL DE PIERNA) */}
        <mesh 
        geometry={nodes.Object_25.geometry} 
        material={materials.defaultMat_2}>

        </mesh>

        {/* ABDUCTORES */}
        <mesh 
          geometry={nodes.Object_27.geometry} 
          material={materials.defaultMat_1}>

        </mesh>

        {/* HUESOS DE LAS MANOS Y PIES */}
        <mesh 
          geometry={nodes.Object_29.geometry} 
          material={materials.material_0}>

        </mesh>

        {/* ANTEBRAZO */}
        <mesh 
          geometry={nodes.Object_31.geometry} 
          material={materials.defaultMat_0}>

        </mesh>

        {/* BICEPS */}
        <mesh 
          onPointerOver={handleHover}
          onPointerOut={handleHoverEnd}
          onClick={handleBicepsClick}
          ref={bicepsRef}
          geometry={nodes.Object_33.geometry} 
          material={materials.defaultMat}>
            <meshStandardMaterial/>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/humano.gltf')
